CREATE TABLE users(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    email VARCHAR NOT NULL UNIQUE,
    role INT NOT NULL ,
    status INT NOT NULL
);

INSERT INTO users (username, password, email, role, status) VALUES ('user','$2a$10$nNF3Ue6XRSeGYLRU9QKpHu/kOEqJ6a6uCV4bMR5Kqt.PLZRmHUNxi','user@mail.com',0,0);
INSERT INTO users (username, password, email, role, status) VALUES ('admin','$2a$10$amsF/TeQ8JwTVtR./DEXFe7LN8.2uTN/08kZ9LUSn0D1rKkk3XXhK','admin@mail.com',1,0);
